name: Auto-generate PR Documentation (AWS Bedrock)

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  generate-documentation:
    # Only run when PR is merged and not created by bots (prevents compute waste)
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.type != 'Bot' &&
      !startsWith(github.event.pull_request.title, 'docs: Add documentation for PR')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write # Required for OIDC
    
    steps:
      # Configure AWS credentials using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-west-2
      
      # Generate GitHub App token if using custom app
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      
      # Run the documentation action
      - uses: anthropics/claude-code-pr-autodoc-action@v1
        with:
          # Use Bedrock with cross-region inference
          model: "anthropic.claude-3-7-sonnet-20250219-beta:0"
          use_bedrock: "true"
          github_token: ${{ steps.app-token.outputs.token }}
          
          # Other configuration options
          min_lines_changed: '50'
          documentation_directory: 'docs/prs'